const urbexLocation = [
    {
        id:0,
        title:"greenLand",
        city:"Milano",
        numPhoto:10,
    },
    {
        id:1,
        title:"ManicomioMobello",
        city:"Milano",
        numPhoto:5,
    },
    {
        id:2,
        title:"ManicomioVolterra",
        city:"Volterra",
        numPhoto:16,
    },
    {
        id:3,
        title:"CityRoma",
        city:"Roma",
        numPhoto:30,
    },
    {
        id:4,
        title:"CityPisa",
        city:"Pisa",
        numPhoto:28,
    },
    {
        id:5,
        title:"CityVolterra",
        city:"Volterra",
        numPhoto:28,
    },
]

module.exports = {urbexLocation}